# Generated by Django 4.2.11 on 2024-05-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
