# Generated by Django 4.2.11 on 2024-05-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_studentregistration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentregistration',
            table='app1_learning',
        ),
    ]
